spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: UrlStore
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher        
  mongodb:
    embedded:
      version: 5.0.7 
server:
  error:
    include-message: always   
    
